apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    description: LAN homebridge
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: homebridge
    location: lan
  name: homebridge
  selfLink: /apis/extensions/v1beta1/namespaces/lan/deployments/homebridge
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: homebridge
      location: lan
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        description: LAN homebridge
      creationTimestamp: null
      labels:
        k8s-app: homebridge
        location: lan
      name: homebridge
    spec:
      containers:
      - env:
        - name: tz
          value: Europe/Berlin
        image: oznu/homebridge
        imagePullPolicy: Always
        name: homebridge
        ports:
        - containerPort: 51827
          hostPort: 51827
          protocol: TCP
        - containerPort: 5353
          hostPort: 5353
          protocol: TCP
        volumeMounts:
        - mountPath: /homebridge
          name: k8s-cfg-homebridge
        resources: {}
        securityContext:
          privileged: true
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
      - name: k8s-cfg-homebridge
        hostPath:
          path: /root/k8s-cfg/homebridge
          type: Directory
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        location: lan
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
